{% set name = "delvewheel" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: fde628c128536665c3899c47f4df849c905e7f3f850948639b02f209c1cb289f

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.7
    - pefile

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
