{% set python_min = python_min|default("3.8") %}
{% set name = "delvewheel" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: 4b4219586bd0dbd0ebe28e9fd856c4ec05b7a5094a24a753b736151f92d897e5

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.1.0
    - pip
  run:
    - python >={{ python_min }}
    - pefile >=2024.8.26

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
