{% set python_min = python_min|default("3.8") %}
{% set name = "delvewheel" %}
{% set version = "1.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: ae445f35f411c367f5b350431ac5f1435af8128bff31ccf34035a409704da8c6

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.1.0
    - pip
  run:
    - python >={{ python_min }}
    - pefile >=2024.8.26

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
