{% set python_min = python_min|default("3.8") %}
{% set name = "delvewheel" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: 514a2fb37bdac7faf9bc54c5f811fb88ad5107aa67f1828931ff67e21366d4b2

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.1.0
    - pip
  run:
    - python >={{ python_min }}
    - pefile >=2024.8.26

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
