{% set name = "delvewheel" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: 86f7a482367bfb05b937deb79972e3fa50fdb113f1a604a84232325ef1918d62

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.7
    - pefile
    - machomachomangler

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
