{% set name = "delvewheel" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/delvewheel-{{ version }}.tar.gz
  sha256: 66359af0afbb1846960d6b19c5b9243a69b30d2543f8780f123580a061a17c70

build:
  entry_points:
    - delvewheel = delvewheel.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pefile
    - machomachomangler

test:
  imports:
    - delvewheel
  commands:
    - pip check
    - delvewheel --help
  requires:
    - pip

about:
  home: https://github.com/adang1345/delvewheel
  summary: Self-contained wheels for Windows
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
