schema_version: 1

context:
  version: "1.13.2"

package:
  name: delvewheel
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/delvewheel/delvewheel-${{ version }}.tar.gz
  sha256: e04b40d8186d80d3ef74dc8571b5d15026b7a8858e89312692a2b09fbcc67b0e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - delvewheel = delvewheel.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - pip
  run:
    - python >=${{ python_min }}
    - pefile >=2024.8.26

tests:
  - python:
      imports:
        - delvewheel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - delvewheel --help

about:
  summary: Self-contained wheels for Windows
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adang1345/delvewheel
  documentation: https://github.com/adang1345/delvewheel/blob/master/README.md

extra:
  recipe-maintainers:
    - ocefpaf
